name: 🧪 Static analysis

on:
  pull_request:
    types: [edited, opened, synchronize]
    branches: ['main']
  workflow_dispatch:

jobs:
  code-analysis:
    name: "Code analysis, test and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Unit tests
        run: pnpm run tests:headless
      - name: Linter
        run: pnpm run lint

      - name: Write environments
        run: |
          echo "${{vars.DOCS_ENV}}" >> projects/docs/src/environments/environment.ts

      - name: Build
        run: pnpm run build:prd
